server:
  port: 8876
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  application: 
    name: 'mymall-manager-ms'
  datasource:
    username: root
    password: 123456
    url: 'jdbc:mysql://localhost:3306/shoppingdb?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai'
  activemq:
    broker-url: tcp://127.0.0.1:61616
    user: admin
    password: admin

pagehelper:
  helper-dialect: mysql
  reasonable: true

# MinIO对象存储相关配置
minio:
  endpoint:  http://127.0.0.1:9000 #MinIO服务所在地址
  bucketName: mall #存储桶名称
  accessKey: minioadmin #访问的key
  secretKey: minioadmin #访问的秘钥
file:
  staticAccessPath:  '/upload/**'
  uploadFolder:  'D:\\file'
 