server:
  port: 8817
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  data:
    solr:
      host: http://127.0.0.1:8081/solr
  datasource:
    username: root
    password: 123456
    url: 'jdbc:mysql://localhost:3306/shoppingdb?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai'
  application:
    name: 'mymall-search-ms'
  activemq:
    broker-url: tcp://127.0.0.1:61616
    user: admin
    password: admin
 